<template>
  <div>
    <CommonFormSection title="Final Approved PDF">
      <CommonPlaceholderBox label="Generated PDF Preview Placeholder" height="200px" />
      <div v-if="doc" class="mt-4 space-y-1">
        <CommonReadOnlyField label="Proposal ID" :value="doc.proposalId" />
        <CommonReadOnlyField label="Reference ID" :value="doc.referenceId" />
        <CommonReadOnlyField label="Document Control Number" :value="doc.documentControlNumber" />
        <CommonReadOnlyField label="Version" :value="doc.versionNumber" />
        <CommonReadOnlyField label="Generated Date" :value="doc.generatedDate" />
        <CommonReadOnlyField label="Generated Time" :value="doc.generatedTime" />
        <CommonReadOnlyField label="Generated By" :value="doc.generatedBy" />
        <CommonReadOnlyField label="Verification Code" :value="doc.verificationCode" />
        <CommonReadOnlyField label="File Status" :value="doc.fileStatus" />
        <CommonPlaceholderBox label="QR Code Placeholder" height="80px" />
      </div>
      <div v-else class="mt-4 text-sm text-gray-400">No final PDF generated yet.</div>
    </CommonFormSection>
  </div>
</template>

<script setup lang="ts">
defineProps<{ doc: any }>()
</script>
